version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout      
      - ruby/bundle-install
      - run:
          name: Update bundler
          command: bundle update --bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Install Jekyll!
          command: gem install jekyll
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: Build Vue
          command: npm run build
      - run:
          name: Bundle Site (The Jekyll Way)
          command: jekyll build

